apiVersion: v1
kind: Service
metadata:
  name: {{ include "product.fullname" . }}
  labels:
    {{- include "product.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9001
      protocol: TCP
      name: http
      nodePort: 30001
  selector:
    {{- include "product.selectorLabels" . | nindent 4 }}
